on:
  push:
    paths-ignore:
      - README.md
      - LICENSE.md
      - 'man/**'
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

name: R-CMD-check

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release',  syle-here: 'no'}
          - {os: windows-latest, r: 'release',  syle-here: 'no'}
          - {os: ubuntu-latest,  r: 'devel',    syle-here: 'no', http-user-agent: 'release'}
          - {os: ubuntu-latest,  r: 'oldrel-1', syle-here: 'no'}
          - {os: ubuntu-latest,  r: 'release',  syle-here: 'yes'}
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-results: never
          upload-snapshots: false

      - name: Upload check results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
          if-no-files-found: ignore

      - name: Upload snapshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-testthat-snapshots
          path: check/**/tests*/testthat/_snaps
          if-no-files-found: ignore

      - name: Trigger next workflow
        if: ${{ github.event_name == 'push' && matrix.config.syle-here == 'yes' && success() }}
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: trigger-workflow-style
          client-payload: '{"ref": "${{ github.ref }}"}'
